---
- name: lab05 - cv_container_v3 lab
  hosts: cv_server
  connection: local
  gather_facts: no
  vars:
    - CVP_CONTAINERS:
        TRAINING:
          parentContainerName: Tenant
  tasks:
    - name: "Configure containers on {{inventory_hostname}}"
      arista.cvp.cv_container_v3:
        topology: "{{CVP_CONTAINERS}}"
        state: absent
      register: CVP_CONTAINERS_RESULT
    - name: "Display cv_configlet result"
      debug:
        msg: "{{CVP_CONTAINERS_RESULT}}"
