pstree -A | egrep -i "(http|apache)"  
pstree -A | egrep -i "(mysql|postgress)" 
pstree -A | egrep -i "(tomcat)"  
pstree -A | egrep -i "(smbd)"
pstree -A | egrep -i "(nagios)"
pstree -A | egrep -i "(munin)"
