---
- name: Run commands on remote LAB devices
  hosts: lab
  gather_facts: false
  connection: ansible.netcommon.httpapi
  pre_tasks:
    - include_vars: "auth.yaml"

  tasks:
    - name: run show version on remote devices
      eos_command:
        provider: "{{arista_credentials}}"
        commands: "show version"

