# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provision "shell", path: "bootstrap.sh"
  # config.vm.provision "shell", path: "ansible.sh"
  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 1
    vb.memory = 4096
  end

  # ---

  config.vm.define "jo" do |jo|
    jo.vm.box = "bento/centos-7.9"
    jo.vm.hostname = "jo"
    jo.vm.network "private_network", ip: "172.20.99.101"
  end
 
  # ---

end
