* openstack undercloud install, tasks 30m near

* 2021-06-30 05:35:12,369 ERROR: At least 7680 MB of memory is required for undercloud installation.
A minimum of 8 GB is recommended. Only detected 5838 MB

* libfacter was not found. Please make sure it was installed to the expected location
https://www.programmersought.com/article/68485349963/
yum downgrade leatherman

* 1 packages excluded due to repository priority protections

rdo-qemu-ev/x86_64/primary_db  FAILED 99% [==================================================================-]  11
http://mirror.centos.org/centos/7/virt/x86_64/kvm-common/repodata/59fdb3e078ee7d351fd5b099b30f75661fde8fc5b3d38f6b3ec89825b179d769-primary.sqlite.bz2: [Errno 12] Timeout on http://mirror.centos.org/centos/7/vi
/59fdb3e078ee7d351fd5b099b30f75661fde8fc5b3d38f6b3ec89825b179d769-primary.sqlite.bz2: (28, 'Operation too slow. Less than 1000 bytes/sec transferred the last 30 seconds')
Trying other mirror.
(7/7): rdo-qemu-ev/x86_64/primary_db
1 packages excluded due to repository priority protections

* import json

but ipmi only not ilo

* 

lldp
eth0, eth1, eth2, eth3
numa
ironic python agent
biosdevname -i eth2 fail
lshw
iptables
Temp
inspector.py
172.20.99.1:5050
BOOTIF=10..:ee
192.168.25.52
192.168.25.1

*

[root@s001 ~]# biosdevname -i enp3s0f0
em1
[root@s001 ~]# biosdevname -i enp3s0f1
em2

