choco install 7zip
choco install adobereader
choco install camstudio
choco install clisp
choco install dia
choco install freemind
choco install filezilla
choco install ghostscript
choco install gimp
choco install git
choco install graphviz
choco install googlechrome
choco install firefox
choco install heidisql
choco install imageresizerapp
choco install itunes
choco install jre8
choco install make
# choco install --allow-empty-checksums nanumfont
# choco install -y nanum-gothic-coding-font
choco install vagrant
choco install vim
choco install virtualbox
choco install vlc
choco install vscode
choco install windirstat
choco install winpcap
choco install winscp
choco install wireshark
choco install xming
