---
- hosts: localhost
  become: yes
  tasks:
  - debug: msg="Ansible is working!"
  - name: pkg
    yum:
      name:
      - psmisc
      - sysstat

  - name: tz
    timezone:
      name: Asia/Seoul

  - name: systemd
    systemd:
      name: "{{ item }}"
      state: started
      enabled: yes
    with_items:
      - rc-local
      - chronyd
      - sysstat
