---
- hosts: localhost
  become: yes
  gather_facts: no
  tasks:
  # - name: tz
  #   timezone:
  #     name: Asia/Seoul

  # - name: pkg
  #   yum:
  #     name:
  #       - psmisc
  #       - sysstat
  #       - emacs-nox
  #       - vim
  #       - wget

  # - name: systemd
  #   systemd:
  #     name: "{{ item }}"
  #     state: started
  #     enabled: yes
  #   with_items:
  #     - rc-local
  #     - chronyd
  #     - sysstat

  # - debug:
  #     msg: "Ansible is working!"

  - name: try to debug
    debug:
      msg: "hello, world"

  - name: package installation
    systemd:
      name: "{{ item }}"
      state: started
      enabled: yes
    with_items:
      - sysstat

  - name: uptime
    command: >
      uptime
    register: uptime

  - name: echoing
    debug:
      msg: "{{ uptime }}"
