---
- hosts: localhost
  become: yes
  gather_facts: no

  tasks:
  - debug:
      msg="Ansible is working!"

  - name: pkg
    yum:
      name:
        - psmisc
        - sysstat
        - vim
        - httpd
        - nginx
        - mariadb
        - wget

  - name: tz
    timezone:
      name: Asia/Seoul

  - name: systemd
    systemd:
      name: "{{ item }}"
      state: started
      enabled: yes
    with_items:
      - rc-local
      - chronyd
      - sysstat
