---
- hosts: all
  tasks:
  - name: ping and pong
    ping:
    
  # - name: pkg installation only not configure
  #   dnf:
  #     name:
  #     - psmisc
  #     - sysstat

  # - name: try to debug
  #   debug:
  #     msg: "hi"

  # - name: tz
  #   timezone:
  #     name: Asia/Seoul

  # - name: systemd
  #   systemd:
  #     name: "{{ item }}"
  #     state: started
  #     enabled: yes
  #   with_items:
  #     - rc-local
  #     - chronyd
  #     - sysstat

