---
- hosts: conn
  tasks:
  - name: pkg
    yum:
      name:
      - psmisc
      - sysstat

  - name: tz
    timezone:
      name: Asia/Seoul

  - name: systemd
    systemd:
      name: "{{ item }}"
      state: started
      enabled: yes
    with_items:
      - rc-local
      - chronyd
      - sysstat
  - name: debug
    debug:
      msg: debug

