* TODO [2022-01-21 Fri] bash go.sh fail with No rule to make target

$ bash go.sh
'.  Stop. No rule to make target 'check
'.  Stop. No rule to make target 'start
'.  Stop. No rule to make target 'check

jack@DESKTOP-73HP56K ~/tmp/t-shell/kubernetes/kubeadm
$ cat go.sh
make -f makefile-for-m check
make -f makefile-for-m start
make -f makefile-for-m check

* TODO [2022-02-18 Fri] install to fai1 / kvm and docker.sh fail 

** issue

W: Failed to fetch https://download.docker.com/linux/debian/dists/bullseye/InRelease  Invalid response from proxy: HTTP/1.0 403 CONNECT denied (ask the admin to allow HTTPS tunnels)     [IP: 192.168.33.250 3142]
W: Some index files failed to download. They have been ignored, or old ones used instead.


** using pkg format

https://docs.docker.com/engine/install/debian/

   84  apt install wget
   85  wget https://download.docker.com/linux/debian/dists/bullseye/pool/stable/amd64/containerd.io_1.4.12-1_amd64.deb
   86  wget https://download.docker.com/linux/debian/dists/bullseye/pool/stable/amd64/docker-ce-cli_20.10.12~3-0~debian-bullseye_amd64.deb
   87  wget \https://download.docker.com/linux/debian/dists/bullseye/pool/stable/amd64/docker-ce-rootless-extras_20.10.12~3-0~debian-bullseye_amd64.deb
   88  wget https://download.docker.com/linux/debian/dists/bullseye/pool/stable/amd64/docker-ce_20.10.12~3-0~debian-bullseye_amd64.deb
   89  wge thttps://download.docker.com/linux/debian/dists/bullseye/pool/stable/amd64/docker-scan-plugin_0.12.0~debian-bullseye_amd64.deb

dpkg -i *.deb

https://download.docker.com/linux/debian/dists/bullseye/pool/stable/amd64/

   97  apt install iptables -y
   98  apt --fix-broken install

역시나인가?

* TODO [2022-02-18 Fri] install to fai1 / kvm and the-k.sh fail too

** issue

root@fai5:~/t-shell/kubernetes/kubeadm# sh the-k.sh 
Err:1 https://apt.kubernetes.io kubernetes-xenial InRelease
  Invalid response from proxy: HTTP/1.0 403 CONNECT denied (ask the admin to allow HTTPS tunnels)     [IP: 192.168.33.250 3142]
Hit:2 http://deb.debian.org/debian bullseye InRelease
Hit:3 http://fai-project.org/download bullseye InRelease
Hit:4 http://deb.debian.org/debian-security bullseye-security InRelease
Reading package lists...
W: Failed to fetch https://apt.kubernetes.io/dists/kubernetes-xenial/InRelease  Invalid response from proxy: HTTP/1.0 403 CONNECT denied (ask the admin to allow HTTPS tunnels)     [IP: 192.168.33.250 3142]
W: Some index files failed to download. They have been ignored, or old ones used instead.


** so


Package: kubeadm
Version: 1.23.4-00
Installed-Size: 44164
Maintainer: Kubernetes Authors <kubernetes-dev+release@googlegroups.com>
Architecture: amd64
Depends: kubelet (>= 1.19.0), kubectl (>= 1.19.0), kubernetes-cni (>= 0.8.7), cri-tools (>= 1.19.0)
Description: Kubernetes Cluster Bootstrapping Tool
 The Kubernetes command line tool for bootstrapping a Kubernetes cluster.
Homepage: https://kubernetes.io
Filename: pool/kubeadm_1.23.4-00_amd64_0950936fcedab589d0b80fa38513837435205490196ed0a80badb7c68fae8753.deb
Priority: optional
SHA256: 0950936fcedab589d0b80fa38513837435205490196ed0a80badb7c68fae8753
Section: misc
Size: 8582916

https://packages.cloud.google.com/apt/pool/kubelet_1.23.4-00_amd64_980f695075569605bb36bc1879988fad9b4f894ab598195bfb325c1c73163be0.deb

kubelet (>= 1.19.0), kubectl (>= 1.19.0), kubernetes-cni (>= 0.8.7), cri-tools (>= 1.19.0)

Version: 1.23.4-00


  140  wget https://packages.cloud.google.com/apt/pool/kubeadm_1.23.4-00_amd64_0950936fcedab589d0b80fa38513837435205490196ed0a80badb7c68fae8753.deb
  141  wget https://packages.cloud.google.com/apt/pool/kubelet_1.23.4-00_amd64_980f695075569605bb36bc1879988fad9b4f894ab598195bfb325c1c73163be0.deb
  146  wget https://packages.cloud.google.com/apt/pool/kubectl_1.23.4-00_amd64_8665604e01fca125404270822c0a15e1964e397bbe411277f49a6eb13a9d6fef.deb
  152  wget https://packages.cloud.google.com/apt/pool/kubernetes-cni_0.8.7-00_amd64_ca2303ea0eecadf379c65bad855f9ad7c95c16502c0e7b3d50edcb53403c500f.deb
  154  wget https://packages.cloud.google.com/apt/pool/cri-tools_1.19.0-00_amd64_b6fdfd86c8a3665ab10b9bd9565354977cd5abbaefeb2ee953bc4a13fe7d3326.deb

apt install socat ebtables ethtool conntrack


* [2022-02-18 Fri] 

root@fai5:~/t-shell/kubernetes/kubeadm# kubeadm init --pod-network-cidr=10.244.0.0/16
[init] Using Kubernetes version: v1.23.4
[preflight] Running pre-flight checks
	[WARNING Swap]: swap is enabled; production deployments should disable swap unless testing the NodeSwap feature gate of the kubelet
	[WARNING Hostname]: hostname "fai5" could not be reached
	[WARNING Hostname]: hostname "fai5": lookup fai5 on 192.168.33.250:53: no such host

error execution phase preflight: [preflight] Some fatal errors occurred:
	[ERROR Mem]: the system RAM (975 MB) is less than the minimum 1700 MB
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
To see the stack trace of this error execute with --v=5 or higher
root@fai5:~/t-shell/kubernetes/kubeadm# 
