help:
	@cat makefile | grep ^[a-z] | grep -v help | sed -e 's/://' -e 's/^/- /'
all:
	@echo yet
# ---
os:
	sh os.sh
docker:
	sh docker.sh
the-k:
	sh the-k.sh

# ---
dashboard:
	sh dashboard.sh
bash:
	sh bash.sh

# ---
test:
	sh test.sh
deploy:
	sh deploy.sh
check:
	sh check.sh

# ---
clean:
	sh clear.sh
