# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provision "shell", path: "bootstrap-for-debian-type.sh"
  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 4
    vb.memory = 4096
  end

  # ---

  config.vm.define "jo" do |jo|
    jo.vm.box = "bento/debian-11"
    jo.vm.hostname = "jo"
    jo.vm.network "private_network", ip: "192.168.56.100"
  end

  # ---
  
end
