---
- name: Playbook to demonstrate cvp modules.
  hosts: cv_server
  connection: local
  gather_facts: no
  collections:
    - arista.cvp
  tasks:
  - name: '#01 - Collect devices facts from {{inventory_hostname}}'
    arista.cvp.cv_facts_v3:

  - name: '#02 - Collect devices facts from {{inventory_hostname}}'
    arista.cvp.cv_facts_v3:
      facts:
        - configlets
    register: FACTS_DEVICES
  
  - name: '#03 - Collect devices facts from {{inventory_hostname}}'
    arista.cvp.cv_facts_v3:
      facts:
        - devices
        - containers
    register: FACTS_DEVICES
