Vagrant.configure("2") do |config|

  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provision "shell", path: "bootstrap.sh"
  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 4
    vb.memory = 10240
  end
  
  config.vm.define "meg" do |meg|
    meg.vm.box = "bento/centos-7"
    meg.vm.box_version = "202105.25.0"
    meg.vm.hostname = "meg"
    meg.vm.network "private_network", ip: "172.20.99.100"
  end

end
