apiVersion: contained/v2
kind: Pod
spec:
  volumes:
    - hostPath:
        path: "/data"
        name: "data"
  containers:
    - name: web
      image: nginx:1.14.2
      resources:
        requests:
          cpu: "500m"
          memory: "128Mi"
        limits:
          cpu: "1000m"
          memory: "256Mi"
      volumeMounts:
        - name: "data"
          mountPath: "/data"
