# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provision "shell", path: "bootstrap.sh"
  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 1
    vb.memory = 4096
  end

  # ---

  config.vm.define "meg" do |meg|
    meg.vm.box = "bento/centos-8.4"
    meg.vm.hostname = "meg"
    meg.vm.network "private_network", ip: "172.20.99.100"
    meg.vm.network "private_network", ip: "172.20.99.101"
  end

  config.vm.define "jo" do |jo|
    jo.vm.box = "bento/ubuntu-18.04"
    jo.vm.hostname = "jo"
    jo.vm.network "private_network", ip: "172.20.99.110"
    jo.vm.network "private_network", ip: "172.20.99.111"
  end

  config.vm.define "beth" do |beth|
    beth.vm.box = "bento/centos-7.9"
    beth.vm.hostname = "beth"
    beth.vm.network "private_network", ip: "172.20.99.120"
    beth.vm.network "private_network", ip: "172.20.99.121"
  end

  config.vm.define "amy" do |amy|
    amy.vm.box = "bento/centos-7.9"
    amy.vm.hostname = "amy"
    amy.vm.network "private_network", ip: "172.20.99.130"
    amy.vm.network "private_network", ip: "172.20.99.131"
  end  
  
  # ---
  
end
