# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provision "shell", path: "bootstrap.sh"
  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 2
    vb.memory = 2048
  end

  # ---

  config.vm.define "meg" do |meg|
    meg.vm.box = "bento/centos-8.4"
    meg.vm.hostname = "meg"
    meg.vm.network "private_network", ip: "172.20.99.100"
    meg.vm.network "private_network", ip: "172.20.99.101"
  end

  # config.vm.define "jo" do |jo|
  #   jo.vm.box = "bento/centos-8.4"
  #   jo.vm.hostname = "jo"
  #   jo.vm.network "private_network", ip: "172.20.99.200"
  #   jo.vm.network "private_network", ip: "172.20.99.201"
  # end
  
  # ---
  
end
