Vagrant.configure("2") do |config|

  config.vm.synced_folder ".", "/vagrant", disabled: true
  # config.vm.provision "shell", path: "bootstrap.sh"
  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 1
    vb.memory = 1024
  end
  
  config.vm.define "meg" do |meg|
    meg.vm.box = "bento/centos-7"
    meg.vm.box_version = "202105.25.0"
    meg.vm.hostname = "meg.foo.com"
    meg.vm.network "private_network", ip: "172.20.99.1"
    meg.vm.provider :virtualbox do |vb|
      # vb.customize ["modifyvm", :id, "--cpus", "4"]
      vb.cpus = 4
      # vb.customize ["modifyvm", :id, "--memory", "10240"]
      # vb.memory = 8192
      vb.memory = 10240
    end
    meg.vm.provision "shell", path: "bootstrap.sh"
    # vagrant plugin install vagrant-timezone
    # if Vagrant.has_plugin?("vagrant-timezone")
    #   config.timezone.value = "Asia/Seoul"
    # end
end

end
