---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: pingping
      ping:

    - name: get uptime
      shell: uptime
      register: uptime

    - name: chk uptime
      debug:
        var: uptime.stdout
      tags: [being]

    - name: uptime with rc and when
      debug:
        var: uptime.rc
      when: uptime.rc != 0
        
    - name: get python version
      shell: python -V
      register: py

    - name: chk python version
      debug:
        var: py.stdout.split(' ')[1]
        
